[package]
name = "changelogen"
version = "0.0.0"
edition = "2024"
rust-version = "1.89"

[lib]
name = "changelogen"
path = "src/lib.rs"

[dependencies]
git2 = "0.20"
semver = { version = "1", features=["serde"] }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
thiserror = "2"
serde = { version = "1", features=["derive"] }
serde_json = "1"
toml_edit = { version = "0.23", features=["serde"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features=["env-filter"] }
rayon = { version = "1", optional = true }
jiff = "0.2"
reqwest = { version = "0.12", default-features = false, features=["rustls-tls", "json"] }
demand = "1.7"
dashmap = { version = "6", optional = true }
git-conventional = "0.12"
# Minimal Tokio features used (runtime + macros + process)
tokio = { version = "1", features = ["rt-multi-thread", "macros", "process"] }

[dev-dependencies]
insta = { version = "1", features=["yaml"] }
assert_fs = "1"
tempfile = "3"
proptest = "1"
criterion = { version = "0.7", features=["html_reports"] }
cargo-deny = "0.18"
# nextest is run via cargo-nextest binary; keep minimal here

