[package]
name = "changelogen"
version = "0.0.0"
authors = ["Muntasir Mahmud <muntasir.joypurhat@gmail.com>"]
edition = "2024"
rust-version = "1.85"
description = "💅 Beautiful Changelogs using Conventional Commits"
readme = "README.md"
repository = "https://github.com/MuntasirSZN/changelogen-rs"
license = "MIT"
keywords = [
  "changelog",
  "cli",
  "conventional-commit",
  "generator",
  "git",
  "markdown",
]
categories = ["command-line-utilities", "development-tools"]

[features]
default = []

[lib]
name = "changelogen"
path = "src/lib.rs"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
dashmap = { version = "6", optional = true }
demand = "1.7"
git2 = "0.20"
git-conventional = "0.12"
jiff = "0.2"
once_cell = "1"
rayon = "1"
regex = "1"
reqwest = { version = "0.12", default-features = false, features = [
  "http2",
  "json",
  "rustls-tls-native-roots-no-provider",
  "socks",
  "system-proxy",
] }
rustls = { version = "0.23.31", default-features = false, features = [
  "aws_lc_rs",
] }
semver = { version = "1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tokio = { version = "1", features = ["macros", "process", "rt-multi-thread"] }
toml_edit = { version = "0.23", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
unicode-normalization = "0.1"

[dev-dependencies]
assert_fs = "1"
cargo-deny = "0.18"
criterion = { version = "0.7", features = ["html_reports"] }
insta = { version = "1", features = ["yaml"] }
proptest = "1"
tempfile = "3"
