# cargo-deny configuration
# https://embarkstudios.github.io/cargo-deny/

[advisories]
# Use v2 configuration format
version = 2
# Ignore advisories for specific IDs
ignore = [
    # paste crate is unmaintained but used only by dev dependency cargo-deny
    "RUSTSEC-2024-0436",
]

[licenses]
# Use v2 configuration format
version = 2
# Allow commonly used permissive licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "CC0-1.0",
    "CDLA-Permissive-2.0",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "OpenSSL",
    "Zlib",
]
# Confidence threshold for license detection
confidence-threshold = 0.8

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"
# Skip certain crates from multiple-version checks
skip = []
# Skip tree display for these crates
skip-tree = []
# Deny specific crates
deny = [
    # Add any crates to deny here
]

[sources]
# Lint level for unknown registries
unknown-registry = "deny"
# Lint level for unknown git sources
unknown-git = "warn"
# Allow git sources from these domains
allow-git = []
