name: CI
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.90.0
          components: clippy,rustfmt
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: Format check
        run: cargo fmt -- --check
      - name: Clippy
        run: cargo clippy -- -D warnings
      - name: Build
        run: cargo build --all --locked
      - name: Install nextest
        run: cargo install cargo-nextest --locked --version ^0.9 || echo "nextest already installed"
      - name: Tests (nextest)
        run: |
          cargo nextest run --all-features --all-targets --locked --profile ci
          cargo test --doc --locked

# Placeholder for cargo-deny integration in later stages
